[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "swap-queue"
version = "0.0.3-beta.1"
description = "A lockfree thread-owned queue whereby tasks are taken by threadsafe stealers in entirety via buffer swapping instead of task popping"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/swap-queue-rs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"

[target.'cfg(loom)'.dependencies]
loom = "0.5.1"

[lib]
doctest = false
