version: "3"

env:
  TARGET: x86_64-apple-darwin

sources:
  - src/**/*.rs

tasks:
  default:
    cmds:
      - task: test-loom

  bench:
    cmds:
      - cargo bench --profile release

  update-benchmarks:
    cmds:
      - task: bench
      - git add target/criterion --force

  test:
    cmds:
      - task: test-doc
      - task: test-miri
      - task: test-loom
      - task: test-sanitizer

  test-doc:
    cmds:
      - cargo test --doc -- --nocapture
    sources:
      - src/**/*.rs

  test-miri:
    cmds:
      - cargo miri test -Z build-std --target $TARGET -- --nocapture
    sources:
      - src/**/*.rs
    env:
      MIRIFLAGS: -Zmiri-ignore-leaks

  test-loom:
    cmds:
      - cargo test -Z build-std --target $TARGET -- --nocapture
    sources:
      - src/**/*.rs
    env:
      RUSTFLAGS: --cfg loom
      LOOM_MAX_PREEMPTIONS: 10

  test-sanitizer:
    cmds:
      - task: test-address-sanitizer
      - task: test-thread-sanitizer
      - task: test-leak-sanitizer

  test-address-sanitizer:
    cmds:
      - cargo test -Z build-std --target $TARGET -- --nocapture
    sources:
      - src/**/*.rs
    ev:
      RUSTFLAGS: -Z sanitizer=address
      ASAN_OPTIONS: suppressions=asan

  test-thread-sanitizer:
    cmds:
      - cargo test -Z build-std --target $TARGET -- --nocapture
    sources:
      - src/**/*.rs
    env:
      RUSTFLAGS: -Z sanitizer=thread
      TSAN_OPTIONS: suppressions=tsan

  test-leak-sanitizer:
    cmds:
      - cargo test -Z build-std --target $TARGET -- --nocapture
    sources:
      - src/**/*.rs
    env:
      RUSTFLAGS: -Z sanitizer=leak
      LSAN_OPTIONS: suppressions=lsan
